grails-app/domain/com/samsoft/em/model/Purchase.groovy
package com.samsoft.em.model


class Purchase {

	String description
	Date dateCreated
	Date dateOfPurchase
	int totalCost;
	UserGroup group // Every purchase is made in context of a group. One user can belong to many groups.
	User createdBy
	

	List<Item> items
	List<Payable> payables
	List<Beneficiary> beneficiaries

	static hasMany = [items:Item,payables:Payable,beneficiaries: Beneficiary]
    static constraints = {
    	description nullable:false,maxLength:1000
    	dateOfPurchase nullable:false,updatable:false
    	totalCost min:1    	
    	group nullable:false
    	description widget:'textArea'
    }

    public int getTotalCost(){
    	int total  = 0;
    	items.each{
    		total+=it.cost
    	}
    	return total
    }
	
	public int getTotalContribution(){
		int total = 0;
		beneficiaries.each{
			total+=it.amountContributed
		}
		return total;
	}

}

grails-app/domain/com/samsoft/em/model/User.groovy
package com.samsoft.em.model

import com.samsoft.em.model.sec.SecUser;
import com.samsoft.em.model.User;


class User  extends SecUser{

	String fname
	String lname
	String mobile
	Date dateCreated
	BankDetails bank;


	static hasMany = [memberships :Membership]

	static constraints = {
		fname  blank:false,maxLength:60
		lname  blank:true,maxLength:50
		mobile nullable:true,minLength:10,maxLength:11,unique:true
		bank   nullable:true
	}
	
	public String toString(){
		"${fname} ${lname}"
	}
	
	public String getFullName(){
		"${fname} ${lname}"
	}
	public int hashCode() {
		super.hashCode()
	}
	
	public boolean equals(Object o){
		if(o==null)
			return false
		if(!getClass().equals(o.getClass()))
			return false;
		User u = (User)o
		return u.username.equals(username)
			
	}
}

grails-app/controllers/com/samsoft/em/controller/PurchaseController.groovy
package com.samsoft.em.controller

import grails.converters.JSON
import grails.plugins.springsecurity.Secured

import org.springframework.dao.DataIntegrityViolationException
import org.springframework.web.servlet.ModelAndView

import com.samsoft.em.model.Beneficiary
import com.samsoft.em.model.Item
import com.samsoft.em.model.Membership
import com.samsoft.em.model.Purchase
import com.samsoft.em.model.User
import com.samsoft.em.model.UserExpense
import com.samsoft.em.model.UserGroup
@Secured(['IS_AUTHENTICATED_REMEMBERED'])
class PurchaseController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]
	def userGroupService
	def springSecurityService
	def purchaseService
	def theUser = null;
	def mailUtilityService
	
	static scope = "session"
	
	private Purchase purchase = null;

    def index() {
        redirect(action: "list", params: params)
    }

	
	def search(){
		def groupSet = Membership.executeQuery("select m.group from Membership m where m.user.id=?",[
			springSecurityService.principal.id
		])
		return new ModelAndView("search", [ groupSet : groupSet ])
	}
	
    def list() {
        //params.max = Math.min(params.max ? params.int('max') : 10, 100)
        //[purchaseInstanceList: Purchase.list(params), purchaseInstanceTotal: Purchase.count()]
		redirect(action: "search")
    }

    def create() {
		def usersGroups = userGroupService.getUsersGroups(springSecurityService.principal.id);
		purchase = null;
		if(params.cancel){
			flash.message= null
			flash.errorMessage = message(code:"action.cancelled",default:"Action Cancelled")
		}
        [purchaseInstance: new Purchase(params),groups:usersGroups]
    }
	
	def cancel(){
		purchase = null
		redirect(action:"create",params:[cancel:"cancel"])
	}

    def savePurchase() {
		
		if(purchase){
			StringBuilder sb = new StringBuilder();
			int totalCost =0;
			int indivCost = 0;
			purchase.items.each {
				totalCost += it.cost
				sb.append(it.description+', ')
			}
			purchase.description=sb.substring(0, sb.length()-2);
			purchase.totalCost = totalCost
			if(!theUser)
				theUser = User.read(springSecurityService.principal.id)
			purchase.createdBy = theUser
			purchase.dateOfPurchase = new Date()
			purchase.group = UserGroup.read(params.group as long)
			
			def benf = purchase.beneficiaries
			purchase.beneficiaries = null;
			indivCost = totalCost/benf.size()
			benf.each{
				new UserExpense(description:purchase.description,amount:indivCost,user:it.user,dateOfExpense:purchase.dateOfPurchase).save(failOnError:true)
				purchase.addToBeneficiaries(it)
			}
			
			def items = purchase.items
			purchase.items = null;
			items.each{
				purchase.addToItems(it)
			}
			def payables = purchase.payables
			purchase.payables = null
			payables.each{
				it.description = purchase.description
				it.createdBy = theUser
				it.group = purchase.group
				purchase.addToPayables(it)
			}
			//TODO: Validate against constraint before saving.
			if (!purchase.save(flush: true,failOnError:true)) {
				log.error("Unable to save the purchase to database.")
				return				
			}
			log.info('Purchase saved successfully.')
			flash.message = message(code: 'purchase.created.successfully',default:"Purchase created successfully")
			def pid = purchase.id
			mailUtilityService.sendPurchaseAlert(purchase)
			purchase = null;   // removed from the session so that it wont be saved again.
			redirect(action: "show", id: pid)
			//return
			// celebrate. purchase was saved successfully.
		}else{
			// session has expired.
		}
		
		/*
        def purchaseInstance = new Purchase(params)
        if (!purchaseInstance.save(flush: true)) {
            render(view: "create", model: [purchaseInstance: purchaseInstance])
            return
        }

		flash.message = message(code: 'default.created.message', args: [message(code: 'purchase.label', default: 'Purchase'), purchaseInstance.id])
        redirect(action: "show", id: purchaseInstance.id)
        */
    }

    def show() {
        /*def purchaseInstance = Purchase.get(params.id)
        if (!purchaseInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'purchase.label', default: 'Purchase'), params.id])
            redirect(action: "list")
            return
        }*/
		if(params.id){
			def purchaseInstance = purchaseService.getPurchaseDetailsByID(params.id as Long)
			if(purchaseInstance)
				[purchaseInstance: purchaseInstance,indvCost:(purchaseInstance.totalCost/purchaseInstance.beneficiaries.size()) as int]
			else
				[purchaseInstance: null]
		}else{
			[purchaseInstance: null]
		}
    }

    def edit() {
        def purchaseInstance = Purchase.get(params.id)
        if (!purchaseInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'purchase.label', default: 'Purchase'), params.id])
            redirect(action: "list")
            return
        }

        [purchaseInstance: purchaseInstance]
    }

    def update() {
        def purchaseInstance = Purchase.get(params.id)
        if (!purchaseInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'purchase.label', default: 'Purchase'), params.id])
            redirect(action: "list")
            return
        }

        if (params.version) {
            def version = params.version.toLong()
            if (purchaseInstance.version > version) {
                purchaseInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'purchase.label', default: 'Purchase')] as Object[],
                          "Another user has updated this Purchase while you were editing")
                render(view: "edit", model: [purchaseInstance: purchaseInstance])
                return
            }
        }

        purchaseInstance.properties = params

        if (!purchaseInstance.save(flush: true)) {
            render(view: "edit", model: [purchaseInstance: purchaseInstance])
            return
        }

		flash.message = message(code: 'default.updated.message', args: [message(code: 'purchase.label', default: 'Purchase'), purchaseInstance.id])
        redirect(action: "show", id: purchaseInstance.id)
    }

    def delete() {
        def purchaseInstance = Purchase.get(params.id)
        if (!purchaseInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'purchase.label', default: 'Purchase'), params.id])
            redirect(action: "list")
            return
        }

        try {
            purchaseInstance.delete(flush: true)
			flash.message = message(code: 'default.deleted.message', args: [message(code: 'purchase.label', default: 'Purchase'), params.id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
			flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'purchase.label', default: 'Purchase'), params.id])
            redirect(action: "show", id: params.id)
        }
    }
	
	/**
	 * Returns group member id and fname as json reponse.
	 * @return Members as JSON
	 */
	def getGroupMembers(){
		def members = null;
		if(params.group){
			members = userGroupService.getGroupMembers(params.group as long);
		}
		render members as JSON;
	}
	
	def renderGroupBeneficiaries(){
		def members = null;
		if(params.group){
			members = userGroupService.getGroupMembers(params.group as long);
			render(template:"benfTable",model:[members:members])
		}
	}
	
	
	/**
	 * This will construct purchase instance from params and use purchase service to compute the payables for this purchase.
	 * @return  will render the table showing the payables.
	 */
	def computePayables(){
		log.info('Will compute purchase now.')
		
		def itemDesc = params.description
		def itemCost = params.cost
		
		def itemList = new ArrayList<Item>(itemCost.size());
		int cartCost = 0;
		if(itemCost.getClass().equals(String.class) ){
			itemList.add(new Item(cost:itemCost as int,description:itemDesc))
			cartCost = itemCost as int
		}else{
			for(int i=0;i<itemCost.size();i++){
				itemList.add(new Item(cost:itemCost[i] as int,description:itemDesc[i]))
				cartCost+= itemCost[i] as int
			}
		}
		
		
		def bids = params.bid
		def amountContributed = params.amountContributed
		int totalContr = 0;
		
		if(bids.getClass().equals(String.class) ){
			// there should be more than 1 beneficiaries.
			render '{"errorMessage":"'+message(code:"atleast.two.benf",default:"There should be atleast two beneficiaries")+'"}' 
			return;
		}
		params.amountContributed.each{
			totalContr += it as int
		}
		
		if(totalContr!=cartCost){
			// this is although handled by javascript.
			render '{"errorMessage":"'+message(code:"cost.mismatch",default:"Total cost must be equal to total contribution")+'"}' 
			return;
		}
		
		def beneficiaries = new ArrayList<Beneficiary>(bids.size());
		for(int i=0;i<bids.size();i++){
			beneficiaries.add(new Beneficiary(amountContributed:params.amountContributed[i] as int,user:User.get(bids[i] as long)))
		}
		
		// purchase is an attribute of this session scoped controller.
		purchase = new Purchase();
		purchase.items = itemList
		purchase.beneficiaries = beneficiaries
		def payables = purchaseService.evaluatePayables(purchase)
		log.info("rendering payable result.");
		int total =0;
		payables?.each{
			total+=it.amount;
		}
		render(template:"computedPayablesTemplate",model:[result:payables,total:total,individualCost:cartCost/beneficiaries.size()])
		return
		
	}
}

grails-app/views/purchase/_benfTable.gsp
<table class="table table-striped" id="id_benfTable"
	style="margin-top: 20px;">
	<thead>
		<tr class="headerRow">
			<th><input type="checkbox" id="id_checkAll" autofocus="autofocus"/></th>
			<th><g:message code="name" default="Name" /></th>
			<th><g:message code="contribution" default="Contribution" /></th>
		</tr>
	</thead>
	<tbody>
		<g:each var="m" in="${members}">
			<tr>
				<td><input type="checkbox" name="bid" value="${m[0]}" /></td>
				<td>
					${m[1]} ${m[2] }
				</td>
				<td style="padding-bottom: 0px;"><input type="number" class="input-small"
					name="amountContributed" value="0" maxlength="6" min="0" 
					max="999999" disabled="disabled" /></td>
			</tr>
		</g:each>
	</tbody>
	<tfoot>
		<tr>
			<td></td>
			<td style="font-weight: 900; font-size: large;">Total</td>
			<td style="font-weight: 900; font-size: large;" id="id_totalContribution"
				>0</td>
		</tr>
	</tfoot>
</table>
<script type="text/javascript">
	$(document).ready(function() {
	
		totalContribution = 0;
		$("input[name=bid]").change(function(){
			$("td:last>input",$(this).parent().parent()).prop("disabled",!$(this).prop("checked"));
			setTotalContribution();
		});

		$("input[name=amountContributed]").change(function(){
			setTotalContribution();
		});
		
		$("#id_checkAll").change(function() {
			var checked = $(this).prop("checked");
			var inp = null;
			$("tbody input[type=checkbox]").each(function(){
				$(this).prop("checked",checked);
				inp = $("td:last>input",$(this).parent().parent());
				inp.prop("disabled",!checked);
			});
			setTotalContribution();
		});


		
	});
	function setTotalContribution(){
		var total = 0;
		$("input[name=amountContributed]:enabled").each(function(){
			total+= (parseInt($(this).val())||0);
		});
		$("#id_totalContribution").html(total);
		totalContribution = total;
		$("#id_totalContri").html(total);
		if(total==totalCost){
			//alert("set hai mamla");
		}
		return total;
	}
</script>

grails-app/views/purchase/_computedPayablesTemplate.gsp
<form method="post" id="id_form">
	<input type="hidden" name="group" id="id_group"/>
	<table class="table table-striped" style="margin-top: 30px">
		<thead style="table-layout: fixed;">
			<tr class="headerRow">
				<th><g:message code="date" default="From" /></th>
				<th><g:message code="date" default="To" /></th>
				<th><g:message code="date" default="Amount" /></th>
			</tr>
		</thead>
		<tbody id="id_payable">
			<g:if test="${result==null || result.size==0 }">
				<tr>
					<td colspan="3"><g:message code="no.payables"
							default="No Payables" /></td>
				</tr>
			</g:if>
			<g:else>
				<g:each in="${result}" var="p">
					<tr id="p${p.id}">
						<td>
							${p.from.fullName}
						</td>
						<td>
							${p.to.fullName}
						</td>
						<td><g:formatNumber number="${p.amount }" type="number" /></td>
					</tr>
				</g:each>
				<tr>
					<td></td>
					<td style="font-weight: 900; font-size: large;"><g:message
							code="total" default="Total" /></td>
					<td style="font-weight: 900; font-size: large;"><g:formatNumber
							number="${total }" type="number" /></td>
				</tr>
			</g:else>
		</tbody>
	</table>
	<div class="row pull-right">
		<input type="button" class="btn btn-primary" value="Save" id="id_saveButton"/>
		<input type="button" class="btn btn-danger" value="Cancel" id="id_cancelButton"/>
	</div>
</form>
<script type="text/javascript">
	$(document).ready(function(){
		
		$("#id_indCostDiv").show();
		$("#id_indvCost").html('<g:formatNumber number="${individualCost }" type="number" />');
		$("#id_group").attr("value",$("#id_groupSelect>option:selected").val());
		$("#id_saveButton").click(function(){
			$("#id_form").attr("action","savePurchase");
			$("#id_form").submit();
		});

		$("#id_cancelButton").click(function(){
			$("#id_form").attr("action","create");
			$("#id_form").submit();
		});
	});
</script>

grails-app/views/purchase/_form.gsp
<%@ page import="com.samsoft.em.model.Purchase" %>



<div class="fieldcontain ${hasErrors(bean: purchaseInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="purchase.description.label" default="Description" />
		
	</label>
	<g:textField name="description" value="${purchaseInstance?.description}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: purchaseInstance, field: 'dateOfPurchase', 'error')} required">
	<label for="dateOfPurchase">
		<g:message code="purchase.dateOfPurchase.label" default="Date Of Purchase" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="dateOfPurchase" precision="day"  value="${purchaseInstance?.dateOfPurchase}"  />
</div>

<div class="fieldcontain ${hasErrors(bean: purchaseInstance, field: 'totalCost', 'error')} required">
	<label for="totalCost">
		<g:message code="purchase.totalCost.label" default="Total Cost" />
		<span class="required-indicator">*</span>
	</label>
	<g:field type="number" name="totalCost" min="1" required="" value="${fieldValue(bean: purchaseInstance, field: 'totalCost')}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: purchaseInstance, field: 'group', 'error')} required">
	<label for="group">
		<g:message code="purchase.group.label" default="Group" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="group" name="group.id" from="${com.samsoft.em.model.UserGroup.list()}" optionKey="id" required="" value="${purchaseInstance?.group?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: purchaseInstance, field: 'beneficiaries', 'error')} ">
	<label for="beneficiaries">
		<g:message code="purchase.beneficiaries.label" default="Beneficiaries" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${purchaseInstance?.beneficiaries?}" var="b">
    <li><g:link controller="beneficiary" action="show" id="${b.id}">${b?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="beneficiary" action="create" params="['purchase.id': purchaseInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'beneficiary.label', default: 'Beneficiary')])}</g:link>
</li>
</ul>

</div>

<div class="fieldcontain ${hasErrors(bean: purchaseInstance, field: 'createdBy', 'error')} required">
	<label for="createdBy">
		<g:message code="purchase.createdBy.label" default="Created By" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="createdBy" name="createdBy.id" from="${com.samsoft.em.model.User.list()}" optionKey="id" required="" value="${purchaseInstance?.createdBy?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: purchaseInstance, field: 'items', 'error')} ">
	<label for="items">
		<g:message code="purchase.items.label" default="Items" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${purchaseInstance?.items?}" var="i">
    <li><g:link controller="item" action="show" id="${i.id}">${i?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="item" action="create" params="['purchase.id': purchaseInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'item.label', default: 'Item')])}</g:link>
</li>
</ul>

</div>

<div class="fieldcontain ${hasErrors(bean: purchaseInstance, field: 'payables', 'error')} ">
	<label for="payables">
		<g:message code="purchase.payables.label" default="Payables" />
		
	</label>
	<g:select name="payables" from="${com.samsoft.em.model.Payable.list()}" multiple="multiple" optionKey="id" size="5" value="${purchaseInstance?.payables*.id}" class="many-to-many"/>
</div>

grails-app/views/purchase/create.gsp
<%@ page import="com.samsoft.em.model.Purchase"%>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Expunto: Group Expense Manager</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="sambhav">

<!-- Le styles -->
<style>
body {
	padding-top: 60px;
	/* 60px to make the container go all the way to the bottom of the topbar */
}
</style>
<link type="text/css" rel="stylesheet"
	href="${resource(dir:'css',file:'bootstrap.css')}" />
<link type="text/css" rel="stylesheet"
	href="${resource(dir:'css',file:'bootstrap-responsive.css')}" />

<!-- Le fav and touch icons -->
<link rel="shortcut icon"
	href="${resource(dir:'images',file:'favicon.ico')}">
<link type="text/css" rel="stylesheet"
	href="${resource(dir:'css',file:'expunto.css')}" />
</head>

<body>

	<g:include view="/nav/topBar.gsp" />
	<div class="container-fluid">
		<div id="id_message">
			<g:if test="${flash.errorMessage }">
					<div class="alert alert-error">
			  			<a class="close" data-dismiss="alert">×</a>
			  			${flash.errorMessage}
					</div>
			</g:if>
			<g:if test="${flash.message }">
					<div class="alert alert-success">
			  			<a type="button" class="close" data-dismiss="alert">×</a>
			  			${flash.message}
					</div>
			</g:if>
		</div>
		<div class="row-fluid">
			<div class="span2" style="padding: 8px 0;">
				<g:include view="nav/nav.gsp"
					params="[menuSelected:4]" />
			</div>

			<div class="span8" id="mainContent">
				<div class="row-fluid">
					<legend  id="id_legend">
						<g:message code="new.purchase" default="New Purchase" />
					</legend>
					<div class="alert alert-info">
						<div class="row">
							<div class="span2">
								<h4>Total Cost: <span id="id_totalCost">0</span></h4>
							</div>
							<div class="span3 offset1">
								<h4>Total Contribution: <span id="id_totalContri">0</span></h4>
							</div>
							<div class="span2 offset0" style="display: none;" id="id_indCostDiv">
								<h4>Individual Cost: <span id="id_indvCost">0</span></h4>
							</div>
						</div>
					</div>
					<div class="tabbable"> <!-- Only required for left/right tabs -->
					  <ul class="nav nav-tabs">
					    <li class="active"><a href="#tab1" data-toggle="tab"><g:message code="items" default="Items" /></a></li>
					    <li><a href="#tab2" data-toggle="tab"><g:message code="beneficiaries" default="Beneficiaries" /></a></li>
					    <li><a href="#tab3" data-toggle="tab"><g:message code="payables" default="Payables" /></a></li>
					  </ul>
					  <div class="tab-content">
					    <div class="tab-pane active" id="tab1">
						    <div class="row-fluid offset0" style="margin-top: 30px">
								<input name="item" autofocus="autofocus" style="width: 135px" autocomplete="on" id="id_Item"
									placeholder="<g:message code="item" default="Item"/>"
									class="input-small" /> <input name="price" id="id_price"
									placeholder="<g:message code="price" default="Price"/>"
									class="input-small" type="number" min="1" maxlength="6"
									size="6" max="999999" />
								<button class="btn " style="margin-bottom: 9px"
									id="id_btnAdd">
									<g:message code="add.item" default="Add Item" />
								</button>
							</div>
							<div class="row-fluid" style="margin-top: 20px">
								<table class="table table-striped" id="id_itemTable">
									<thead>
										<tr class="headerRow">
											<th style="width: 40%">Item</th>
											<th style="width: 40%">Cost</th>
											<th style="width: 20%"><a href="#"  id="id_removeAllItem">x</a> </th>
										</tr>
									</thead>
									<tbody>
										<tr id="id_NoDataRow">
											<td colspan="3">
												<g:message code="no.items.added" default="No Items Added" />
											</td>
										</tr>
									</tbody>
									<tfoot>
										<tr style="display: none;" id="id_totalRow">
											<td style="font-weight: 900; font-size: large;">Total Cost</td>
											<td style="font-weight: 900; font-size: large;" id="id_total" colspan="2"></td>
										</tr>
									</tfoot>
								</table>
							</div>
					    </div>
					    <div class="tab-pane" id="tab2">
					      <div class="row-fluid offset0"  style="margin-top: 10px">
					      	<div class="span3">
					      		<label for="group">Select a group</label>
								<select name="group" id="id_groupSelect" class="span2" style="width: 100%"> 
									<option disabled="disabled" value="-1" selected="selected"><g:message code="choose.group" default="Choose Group"/></option>
									<g:each in="${groups}" var="g">
										<option value="${g.id }">${g.groupName }</option>
									</g:each>
								</select>				
							</div>
						  </div>
						  <div class="row-fluid" id="id_BenfTable">
						  	
						  </div>
					    </div>
					    <div class="tab-pane" id="tab3">
					      
					    </div>
					  </div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- /container -->
	<!-- Le javascript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<g:javascript src="jquery.js"></g:javascript>
	<g:javascript src="utility.js"></g:javascript>
	<g:javascript src="bootstrap-transition.js"></g:javascript>
	<g:javascript src="bootstrap-button.js"></g:javascript>
	<g:javascript src="bootstrap-dropdown.js"></g:javascript>
	<g:javascript src="bootstrap-tab.js"></g:javascript>
	<g:javascript src="bootstrap-alert.js"></g:javascript>
	<script type="text/javascript">
		var totalCost = 0;
		var totalContribution = 0;
		$(document).ready(function(){
			$("ul.nav-tabs>li:first").addClass("active");

			//add item here.
			$("#id_btnAdd").click(function(event){
				var item = $("#id_Item").val().trim();
				if(item.length==0){
					event.preventDefault();
					return;
				}
				var price = $("#id_price").val().trim();
				if(price.length==0||isNaN(price)){
					$("#id_price").val("");
					event.preventDefault();
					return;
				}
				$("#id_Item").val("");
				$("#id_price").val("");
				$("#id_NoDataRow").hide();
				$("#id_totalRow").show();
				price = parseInt(price);
				totalCost+=price;
				$("#id_NoDataRow").parent().append("<tr class=itemx>  <td>"+item+"</td>    <td>"+price+"</td>  <td><a href='#'  onclick=removeItem(this)>x</a>    </td>  </tr>");
				$("#id_total").html(totalCost);
				$("#id_totalCost").html(totalCost);
				
			});

			//remove all items
			$("#id_removeAllItem").click(function(){
				$("tbody>tr:visible",$("#id_itemTable")).remove();
				$("#id_NoDataRow").show();
				$("#id_totalRow").hide();
				totalCost =0;
				$("#id_totalCost").html(0);
			});

			//group select handled here
			$("#id_groupSelect").change(function(){
				$.ajax({
					type	:	"post",
					url		:	"renderGroupBeneficiaries?group="+$("option:selected",$(this)).val(),
					cache	:	true,
					context	:	$("#id_BenfTable"),
					dataType:	"html",
					success	:	function(response){
									$("#id_BenfTable").html(response);
									
								},
					error	:	function(error){
									alert("Error");
								}
				});
			});

			// compute payables here
			$("ul.nav-tabs>li:last").on("show",function(e){
				if(!isNaN(totalContribution)&&!isNaN(totalCost)&&totalContribution>1&&totalCost>1&&totalContribution==totalCost){
					var url = "computePayables?t=8";
					$("tr.itemx").each(function(){
						url+=("&description="+$("td:first",$(this)).html().trim()+"&cost="+$("td:nth-child(2)",$(this)).html().trim());  
					});
					$("input[name=amountContributed]:enabled").each(function(){
						var row = $(this).parent().parent(); 
						url+="&bid="+$("td:first>input[type=checkbox]",row).val()+"&amountContributed="+$("td:last>input[type=number]",row).val();
					});
					$.ajax({
						type	:	"post",
						url		:	 url,
						cache	:	false,
						dataType:	"html",
						success	:	function(response){
										$("#tab3").html(response);
									},
						error	:	function(error){
										alert("Error");
									}
					});	
				}else{
					alert('Invalid stuff');
					e.preventDefault();
					return;
				}
			});

			$("ul.nav-tabs>li:eq(1)").on("shown",function(e){
				$("#id_indCostDiv").hide();
				$("#id_groupSelect").focus();
			});
			$("ul.nav-tabs>li:eq(0)").on("shown",function(e){
				$("#id_indCostDiv").hide();
			});
		});

		function removeItem(item){
			var cost =  $("td:eq(1)", $(item).parent().parent()).html().trim(); 
			totalCost-=parseInt(cost);
			$(item).parent().parent().remove();
			if(totalCost<=0){
				$("#id_NoDataRow").show();
				$("#id_totalRow").hide();
			}else{
				$("#id_total").html(totalCost);
			}
			$("#id_totalCost").html(totalCost);
		}
	</script>

</body>
</html>